version: '3'
services:
    app:
        build: .
        container_name: voteam_app
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mysql
        container_name: voteam_backend
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
